### PR TITLE
Add get_git_branch function so it works with cmder >=1.3.5

### PR DESCRIPTION
**Pull request by nicoddemus**
This function is missing from newest cmdermini versions. Using workaround suggested in https://github.com/AmrEldib/cmder-powerline-prompt/issues/28.

### CODE REVIEW

**Comment by igortg** [comment]
I just synced with upstream since they done some other fixes. Please, check if the current version works for you and let me know.

**Comment by nicoddemus** [comment]
I used their version before submitting this patch, but it lacks the virtual environment indicator. 😕

**Comment by igortg** [comment]
That's the reason of this fork 😉

**Comment by nicoddemus** [comment]
Oh OK let me check

**Comment by nicoddemus** [comment]
Yep, it works now, thanks! Here, have a 🍺!

**Pull request closed without merging**
